name: bpla
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - torch==2.0.0
      - ultralytics==8.0.0
      - hydra-core==1.3.0
      - mlflow==2.0.0
      - dvc==3.0.0
      - black
      - flake8
      - isort
      - pre-commit
