model:
    weights_path: 'models/yolov8s.pt' # ✅ без -seg
    input_size: [640, 640]

data:
    data_path: 'data/data.yaml' # ✅ путь до YAML-файла с train/val

training:
    epochs: 50
    batch_size: 16
    device: 'cuda:0' # или "cpu"
    learning_rate: 0.001
    weight_decay: 0.0005
    task: 'detect' # ✅ обязательно "detect"
