model:
  weights_path: "models/yoloe-11s-seg.pt"
  input_size: [640, 640]

data:
  train_path: "D:\bpla-object-detection\data\train"
  val_path: "D:\bpla-object-detection\data\val"

training:
  epochs: 50
  batch_size: 16
  device: "cpu"
  learning_rate: 0.001
  weight_decay: 0.0005