# ───────────────────── Конфигурация модели ─────────────────────
model:
    # Путь до весов YOLOv8 (предполагается .pt-файл)
    weights_path: 'models/yolov8s.pt'

    # Размер входного изображения (ширина, высота)
    input_size: [640, 640]

# ───────────────────── Конфигурация данных ─────────────────────
data:
    # Путь до YAML-файла с описанием train/val наборов (используется в обучении)
    data_path: 'data/data.yaml'

# ──────────────────── Параметры обучения ────────────────────
training:
    # Количество эпох обучения модели
    epochs: 5

    # Размер батча (число изображений в одном шаге)
    batch_size: 16

    # Устройство для обучения: 'cuda:0' для GPU, 'cpu' для процессора
    device: 'cuda:0'

    # Количество воркеров DataLoader (для ускорения загрузки данных)
    workers: 2

    # Размер изображения, который будет использоваться при обучении
    imgsz: 640

    # Папка, в которую сохраняются результаты обучения
    project: runs/train

    # Название поддиректории для текущего запуска
    name: exp1
